### ISSUE TITLE
Please provide LICENSE

### ISSUE THREAD

**Issue by remicollet** [zetacomponents/UnitTest#4]
From http://www.apache.org/licenses/LICENSE-2.0

     4. Redistribution. 
    ...
       a.You must give any other recipients of the Work or Derivative Works a copy of this License; and
    ...

So please add the LICENSE file in the repository  and in each component repository.

**Comment by derickr** [comment]
These LICENSE files exist as the file "NOTICE". But I'll rename them for you.

**Comment by derickr** [comment]
Fixed.

**Comment by remicollet** [comment]
@derick thanks, but my question was not about the name, but about the content.

From https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text

     Common licenses that require including their texts with all derivative works include ASL 2.0, EPL, BSD and MIT.
     Packagers should point out to upstream that by not including a proper full license text,
     ...

**Comment by derickr** [comment]
You should have mentioned that the first time round :P

**Comment by remicollet** [comment]
yes, sorry... I deeply apologize

**Comment by derickr** [comment]
Fixed now, again. If not, I expect a PR against all ;-)

**Comment by remicollet** [comment]
Thanks a lot, everything seems OK.
